{application,zotonic_mod_email_relay,
             [{description,"Relay incoming e-mails for known users to their private e-mail address."},
              {vsn,"pre-transport+build.6794.ref41e3d06"},
              {registered,[]},
              {applications,[zotonic_core]},
              {env,[]},
              {modules,[mod_email_relay]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[{"GitHub","https://github.com/zotonic/zotonic"}]}]}.
