{application,bert,
             [{description,"BERT Encoder/Decoder"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[bert]},
              {maintainers,["Yuce Tekol"]},
              {licenses,["MIT"]},
              {links,[{"Github","https://github.com/yuce/bert.erl"}]}]}.
