{application,zotonic_mod_tkvstore,
             [{description,"Simple typed key/value store used to store structured data."},
              {vsn,"pre-transport+build.6794.ref41e3d06"},
              {registered,[]},
              {applications,[zotonic_core]},
              {env,[]},
              {modules,[m_tkvstore,mod_tkvstore]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[{"GitHub","https://github.com/zotonic/zotonic"}]}]}.
