{application,dispatch_compiler,
             [{description,"Compile dispatch rules to an Erlang module"},
              {vsn,"1.0.0-alpha1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {maintainers,["Zotonic Team"]},
              {licenses,["Apache 2.0"]},
              {links,[{"GitHub",
                       "https://github.com/zotonic/dispatch_compiler"}]},
              {modules,[dispatch_compiler]}]}.
