{application,zotonic_mod_media_exif,
             [{description,"Extract EXIF information from photos when uploading"},
              {vsn,"pre-transport+build.6794.ref41e3d06"},
              {registered,[]},
              {applications,[zotonic_core]},
              {env,[]},
              {modules,[mod_media_exif]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[{"GitHub","https://github.com/zotonic/zotonic"}]}]}.
